# Generated by Django 4.2.3 on 2026-03-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pptp", "0028_alter_product_source_batch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="source_batch",
            field=models.CharField(
                choices=[
                    ("2026_fish_seafood", "2026 Fish and Seafood Collection"),
                    ("2026_meat_alternatives", "2026 Meat and Alternatives Collection"),
                    (
                        "2026_frozen_refrig_apps",
                        "2026 Frozen and Refrigerated Appetizers Collection",
                    ),
                    (
                        "2026_refrig_sides_entrees",
                        "2026 Refrigerated Sides and Entrees Collection",
                    ),
                    ("2025_snapcan", "SNAP-CAN 2025"),
                    ("2026_baked_goods", "2026 Baked Goods Collection"),
                    ("2026_snack_foods", "2026 Snack Foods Collection"),
                    ("tds", "Total Diet Study"),
                    ("2025_supp_food", "2025 Supplemented Food Collection"),
                    ("2025_frozen_entrees", "2025 Frozen Entrees Collection"),
                ],
                help_text="Product collection batch",
                null=True,
            ),
        ),
    ]
